# Generated by Django 3.2.5 on 2021-07-13 02:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='favorite',
            field=models.ManyToManyField(related_name='boards_favorite_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
