# Generated by Django 3.2.5 on 2021-07-14 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0003_alter_board_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='boards_favorite_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
