# Generated by Django 3.2.5 on 2021-07-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='cards_member', to='members.Member'),
        ),
    ]
